USE	Martian_Database
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(1,1,8)
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(1,3,5)
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(1,5,1)
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(1,6,2)
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(1,8,12)
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(1,9,1)
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(2,4,5)
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(2,8,62)
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(2,10,37)
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(3,2,11)
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(3,7,2)
	INSERT INTO dbo.Inventory(Base_Id, Supply_Id, Quantity)
		VALUES(4,10,91)