USE Martian_Database
	INSERT INTO dbo.Martian(First_Name,Last_Name, Base_Id, Super_Id)
		VALUES('Ray','Bradbury',1,NULL)
	INSERT INTO dbo.Martian(First_Name, Last_Name, Base_Id, Super_Id)
		VALUES('John','Black',4,10)
	INSERT INTO dbo.Martian(First_Name, Last_Name, Base_Id, Super_Id)
		VALUES('Sameul', 'Hinkston',4,2)
	INSERT INTO dbo.Martian(First_Name, Last_Name, Base_Id, Super_Id)
		VALUES('Jeff','Spender',1,9)
	INSERT INTO dbo.Martian(First_Name, Last_Name, Base_Id, Super_Id)
		VALUES('Sam','Parkhill',2,12)
	INSERT INTO dbo.Martian(First_Name, Last_Name, Base_Id, Super_Id)
		VALUES('Elma','Parkhill',3,8)
	INSERT INTO dbo.Martian(First_Name, Last_Name, Base_Id, Super_Id)
		VALUES('Melissa','Lewis',1,1)
	INSERT INTO dbo.Martian(First_Name, Last_Name, Base_Id, Super_Id)
		VALUES('Mark','Watney',3,NULL)
	INSERT INTO dbo.Martian(First_Name, Last_Name, Base_Id, Super_Id)
		VALUES('Beth','Johanssen',1,1)
	INSERT INTO dbo.Martian(First_Name, Last_Name, Base_Id, Super_Id)
		VALUES('Chris','Beck',4,NULL)
	INSERT INTO dbo.Martian(First_Name,Last_Name, Base_Id, Super_Id)
		VALUES('Nathaniel','York',4,2)
	INSERT INTO dbo.Martian(First_Name, Last_Name, Base_Id, Super_Id)
		VALUES('Elon','Musk',2,NULL)
	INSERT INTO dbo.Martian(First_Name, Last_Name, Base_Id, Super_Id)
		VALUES('John','Carter',NULL,8);	