USE Martian_Database
	INSERT INTO dbo.Supply(Name, Description, Quantity)
		VALUES('Solar Panel','Standard 1x1 meter cell', 912)
	INSERT INTO dbo.Supply(Name, Description, Quantity)
		VALUES('Water Filter','This takes things out of your water so its drinkable', 6)
	INSERT INTO dbo.Supply(Name, Description, Quantity)
		VALUES('Duct Tape','A 10 meter roll of duct tabe for ALL your repairs.', 951)
	INSERT INTO dbo.Supply(Name, Description, Quantity)
		VALUES('Ketchup','Its Ketchup...', 206)
	INSERT INTO dbo.Supply(Name, Description, Quantity)
		VALUES('Battery Cell','Standard 1000kAh battery cell for power grid (heavy item).', 17)
	INSERT INTO dbo.Supply(Name, Description, Quantity)
		VALUES('USB 6.0 Cable','Carbon Fiber coated / 15 TBps spool', 42)
	INSERT INTO dbo.Supply(Name, Description, Quantity)
		VALUES('Fuzzy Duster','It gets dusty around here. Be prepared!', 19)
	INSERT INTO dbo.Supply(Name, Description, Quantity)
		VALUES('Mars Bars','The ORIGINAL nutrient bar made with the finest bioengineered ingredients.', 3801)
	INSERT INTO dbo.Supply(Name, Description, Quantity)
		VALUES('Air Filter','Removes 99% of all Martian Dust from your Ventalation Unit.', 23)
	INSERT INTO dbo.Supply(Name, Description, Quantity)
		VALUES('Famous Rays Frozen Pizzza','This Martian favorite is covered in all your favorite toppings. 1 flavor only.', 823)